export const translations = {
    en: {
      language: "LANGUAGE",
      currency: "CURRENCY",
      newsletter: "NEWSLETTER",
      contact: "CONTACT US",
      affiliate: "AFFILIATE",
      categories: "CATEGORIES",
      shop: "SHOP",
      blog: "BLOG",
      pages: "PAGES",
      faq: "FAQ",
      login: "LOGIN / REGISTER",
      wishlist: "WISHLIST",
      compare: "COMPARE",
      support: "24/7 SUPPORT",
      items: "Items",
      searchPlaceholder: "Search",
    },
    az: {
      language: "DİL",
      currency: "VALYUTA",
      newsletter: "BÜLLETEN",
      contact: "BİZİMLƏ ƏLAQƏ",
      affiliate: "TƏRƏFDAŞ",
      categories: "KATEQORİYALAR",
      shop: "MAĞAZA",
      blog: "BLOQ",
      pages: "SƏHİFƏLƏR",
      faq: "SUALLAR",
      login: "GİRİŞ / QEYDİYYAT",
      wishlist: "BƏYƏNİLƏN",
      compare: "MÜQAYİSƏ",
      support: "24/7 DƏSTƏK",
      items: "Məhsullar",
      searchPlaceholder: "Axtarış",
    },
  };
  